// actions related to the app
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_TAB = 'CHANGE_TAB'
export const LOADING_COMPLETE = 'LOADING_COMPLETE'

// actions related to auth
export const AUTHENTICATED_STAFF = 'AUTHENTICATED_STAFF'
export const AUTHENTICATION_LOADED = 'AUTHENTICATION_LOADED'
export const UNAUTHENTICATED_STAFF = 'UNAUTHENTICATED_STAFF'
export const SAVE_STAFF_PROFILE = 'SAVE_STAFF_PROFILE'
export const SAVE_CORPORATION_PROFILE = 'SAVE_CORPORATION_PROFILE'
export const LOCATION_FORWARDING = 'LOCATION_FORWARDING'
export const REMOVE_STAFF_PROFILE = 'REMOVE_STAFF_PROFILE'

export const SAVE_LISTINGS_TO_REDUX = 'SAVE_LISTINGS_TO_REDUX'
export const NEXT_LISTING = 'NEXT_LISTING'
export const SAVE_PREFS = 'SAVE_PREFS'
export const INCREMENT_LIKES = 'INCREMENT_LIKES'
export const INCREMENT_DISLIKES = 'INCREMENT_DISLIKES'
