// actions related to the app
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_TAB = 'CHANGE_TAB'
export const LOADING_COMPLETE = 'LOADING_COMPLETE'
export const TOGGLE_IS_MOBILE = 'TOGGLE_IS_MOBILE'
export const TOGGLE_DROPDOWN = 'TOGGLE_DROPDOWN'
export const SELECT_CITY = 'SELECT_CITY'

// actions related to auth
export const AUTHENTICATED_TENANT = 'AUTHENTICATED_TENANT'
export const AUTHENTICATION_LOADED = 'AUTHENTICATION_LOADED'
export const UNAUTHENTICATED_TENANT = 'UNAUTHENTICATED_TENANT'
export const SAVE_STAFF_PROFILE = 'SAVE_STAFF_PROFILE'
export const SAVE_CORPORATION_PROFILE = 'SAVE_CORPORATION_PROFILE'
export const LOCATION_FORWARDING = 'LOCATION_FORWARDING'
export const REMOVE_TENANT_PROFILE = 'REMOVE_TENANT_PROFILE'
export const TOGGLE_DRAWER_NAV = 'TOGGLE_DRAWER_NAV'
export const TOGGLE_INSTANT_CHARS = 'TOGGLE_INSTANT_CHARS'
export const SAVE_TENANT_PROFILE = 'SAVE_TENANT_PROFILE'
export const SET_TENANT_ID = 'SET_TENANT_ID'
export const UPDATE_PREFERENCES = 'UPDATE_PREFERENCES'

export const SAVE_LISTINGS_TO_REDUX = 'SAVE_LISTINGS_TO_REDUX'
export const SET_CURRENT_LISTING = 'SET_CURRENT_LISTING'
export const NEXT_LISTING = 'NEXT_LISTING'
export const PREV_LISTING = 'PREV_LISTING'
export const SAVE_PREFS = 'SAVE_PREFS'
export const INCREMENT_LIKES = 'INCREMENT_LIKES'
export const DECREMENT_LIKES = 'DECREMENT_LIKES'
export const CHANGE_COMMUTE_MODE = 'CHANGE_COMMUTE_MODE'
export const CHANGE_CARD_SECTION_SHOWN = 'CHANGE_CARD_SECTION_SHOWN'
export const SET_CURRENT_LISTINGS_STACK = 'SET_CURRENT_LISTINGS_STACK'
export const SORT_LISTINGS_BY = 'SORT_LISTINGS_BY'

// actions related to tenant
export const SAVE_TENANT_FAVORITES = 'SAVE_TENANT_FAVORITES'


// Map Actions
export const SET_MAIN_MAP = 'SET_MAIN_MAP'
export const SET_CURRENT_MAP_LOCATION = 'SET_CURRENT_MAP_LOCATION'
export const SET_MAP_LOADED = 'SET_MAP_LOADED'
export const SET_FLAG_PIN_LOCATION = 'SET_FLAG_PIN_LOCATION'
export const SAVE_NEARBY_LOCATIONS = 'SAVE_NEARBY_LOCATIONS'
export const SET_CURRENT_CLICKED_LOCATION = 'SET_CURRENT_CLICKED_LOCATION'
export const SET_MAP_LISTINGS = 'SET_MAP_LISTINGS'
