// actions related to the app
export const CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'
export const CHANGE_TAB = 'CHANGE_TAB'
export const LOADING_COMPLETE = 'LOADING_COMPLETE'

// actions related to auth
export const AUTHENTICATED_STAFF = 'AUTHENTICATED_STAFF'
export const AUTHENTICATION_LOADED = 'AUTHENTICATION_LOADED'
export const UNAUTHENTICATED_STAFF = 'UNAUTHENTICATED_STAFF'
export const SAVE_STAFF_PROFILE = 'SAVE_STAFF_PROFILE'
export const SAVE_CORPORATION_PROFILE = 'SAVE_CORPORATION_PROFILE'
export const LOCATION_FORWARDING = 'LOCATION_FORWARDING'
export const REMOVE_STAFF_PROFILE = 'REMOVE_STAFF_PROFILE'
export const TOGGLE_DRAWER_NAV = 'TOGGLE_DRAWER_NAV'
export const TOGGLE_INSTANT_CHARS = 'TOGGLE_INSTANT_CHARS'
export const SAVE_TENANT_PROFILE = 'SAVE_TENANT_PROFILE'

export const UPDATE_PREFERENCES = 'UPDATE_PREFERENCES'

export const SAVE_LISTINGS_TO_REDUX = 'SAVE_LISTINGS_TO_REDUX'
export const SET_CURRENT_LISTING = 'SET_CURRENT_LISTING'
export const NEXT_LISTING = 'NEXT_LISTING'
export const SAVE_PREFS = 'SAVE_PREFS'
export const INCREMENT_LIKES = 'INCREMENT_LIKES'
export const DECREMENT_LIKES = 'DECREMENT_LIKES'
export const CHANGE_COMMUTE_MODE = 'CHANGE_COMMUTE_MODE'
export const CHANGE_CARD_SECTION_SHOWN = 'CHANGE_CARD_SECTION_SHOWN'
export const LOAD_LOCAL_STORAGE_ACCOUNT = 'LOAD_LOCAL_STORAGE_ACCOUNT'
export const SET_NAME = 'SET_NAME'
export const RESTART_SEARCH = 'RESTART_SEARCH'
export const SET_CURRENT_LISTINGS_STACK = 'SET_CURRENT_LISTINGS_STACK'

// actions related to tenant
export const SAVE_TENANT_FAVORITES = 'SAVE_TENANT_FAVORITES'
