import {
  BLUE_PACKAGE,
  CLEAN_PAPER,
} from './color_packs'

const PACKAGE = BLUE_PACKAGE

export const FONT_FAMILY = PACKAGE.FONT_FAMILY
export const FONT_FAMILY_ACCENT = PACKAGE.FONT_FAMILY_ACCENT
export const BACKGROUND_WEBKIT = PACKAGE.BACKGROUND_WEBKIT
export const BACKGROUND_MODERN = PACKAGE.BACKGROUND_MODERN
export const BACKGROUND_COLOR = PACKAGE.BACKGROUND_COLOR
export const INPUT_BACKGROUND = PACKAGE.INPUT_BACKGROUND
export const INPUT_PLACEHOLDER_COLOR = PACKAGE.INPUT_PLACEHOLDER_COLOR
export const ACCENT_COLOR = PACKAGE.ACCENT_COLOR
export const FONT_COLOR = PACKAGE.FONT_COLOR
export const INVERSE_FONT_COLOR = PACKAGE.INVERSE_FONT_COLOR
